version: '3.8'

services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./front:/usr/share/nginx/html
  
  node:
    image: node:latest
    ports:
      - "3000:3000"
    volumes:
      - ./back:/usr/src/app